DELETE http://localhost:3003/api/blogs/5f4b97abfafbc23b809e51cc
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbiIsImlkIjoiNWY0YjllNTAyMGJmMjM0MjI5ZmJkZDFjIiwiaWF0IjoxNTk4NzkxMjc3fQ.I07QW_8rUrsS5FV-gs6zGzEbtR5ovejAuRtPrqPg4Vk